# @name: azure-cd-pipelines.yml
# @description: ADO CD pipeline for Oracle DB deployment using Liquibase
# @author: Richard Koranteng (https://rkkoranteng.com)
# @changes: refer to CHANGELOG.md

#trigger:
#  branches:
#    include:
#      - main
#  paths:
#    include:
#      - changelog.xml

trigger: none

appendCommitMessageToRunName: false
  
name: $(Database.SID)-$(Build.BuildId)-CD

pool:
  name: $(Agent.PoolName)

variables:
- template: variables.yml

resources:
  pipelines:
    - pipeline: ciBuild          
      source: Database_CI
      trigger:
        branches:
          include:
            - main

stages:

# deploy to Dev
- stage: Dev
  displayName: 'Deploy to Dev'
  jobs:
  - deployment: Deploy_Dev
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: liquibase-artifacts
              path: $(Pipeline.Workspace)

          - task: PowerShell@2
            displayName: 'Liquibase Update'
            inputs:
              targetType: 'inline'
              script: |
                $url = "jdbc:oracle:thin:@//$(Database.Host):$(Database.Port)/$(Database.SID)"
                & "C:\Program Files\liquibase\liquibase.bat" `
                  --changeLogFile=changelog.xml `
                  --url=$url `
                  --username=$(username) `
                  --password=$(password) `
                  update
            workingDirectory: $(Pipeline.Workspace)